# Permalinks
permalink:        pretty

# Setup
title:            HTRC
tagline:          'HathiTrust Research Center'
description:      'HathiTrust Research Center Github Home'
url:              http://htrc.github.io
baseurl:          /

author:
  name:           'HTRC Team'
  url:            http://htrc.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/htrc

# Dependencies
highlighter: rouge
